language: c
os: linux
dist: focal
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager

jobs:
  include:
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: focal
      virt: vm
    - os: linux
      arch: s390x
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64-graviton2
      env: TR_ARCH=local RUN_TESTS=1
      dist: focal
      group: edge
      virt: vm
    - os: linux
      arch: arm64-graviton2
      env: TR_ARCH=local CLANG=1 RUN_TESTS=1
      group: edge
      virt: vm
      dist: bionic
script:
  - sudo uname -a
  - sudo ls -al /dev/kvm
  - sudo systemctl start libvirtd
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm
  - sudo virsh --connect qemu:///system list
